### ISSUE TITLE
error message when attempting login, if the user is already logged in

### ISSUE THREAD

**Issue by aaronrothmann** [fbennets/open-decision#46]
**To Reproduce**
1. Go to the Login Page, insert your Data and press login
2. use the back button on your browser
3. attempt to login a second time

**Expected behavior**
When one clicks on the Login-Button (either on the Main Page (logged out) or on the Login Page) while logged in, automatically redirect to the Main Page (logged in).

**Comment by fbennets** [comment]
This is the expected and correct behaviour, as the error is thrown by the CSRF mechanism, that prevents cross site scripting. The best solution is to build a custom error page to inform the user about the reason for the error. 
For reference:
[Django Doc about CSRF Failure View](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-CSRF_FAILURE_VIEW)
[Stackoverflow Discussion with different solutions](https://stackoverflow.com/questions/26925244/django-how-to-override-the-csrf-failure-template)
