### ISSUE TITLE
Local Setup Dependency Issue

### ISSUE THREAD

**Issue by PhilGarb** [fbennets/open-decision#48]
**Describe the bug**
When trying to installing requirements on a linux based system psycopg2-binary cannot be build from source. 

```bash
Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**To Reproduce**
1. Follow the setup steps in the Readme on linux up to installing the requirements in your virtual python environment. 
2. Run the install requirements step. 
3. It fails with the above error.

**Expected behavior**
No error when installing the requirements.

**Desktop (please complete the following information):**
 - OS: 5.4.2.1 Manjaro 
 - Terminal

**Additional context**
Following the advice of the output and installing psycopg2 manually in the virtual environement, while removing the dependency from requirements, solves the issue, but is probably not the intended method. Is there a readon for the binary instead of the package?

**Comment by fbennets** [comment]
Thanks for reporting the issue, I'll check the next days and get back to you!

**Comment by fbennets** [comment]
Fixed in last commit to JSinterpreter, will be soon merged into master.
Removed psycopg2-binary from requirements.txt as it is not needed anyway and deleted import of jsonfield in some .views.
